//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int ChairID { get; set; }
        public decimal Price { get; set; }
        public int ClientID { get; set; }
        public int CinemaHallID { get; set; }
    
        public virtual Chair Chair { get; set; }
        public virtual CinemaHall CinemaHall { get; set; }
        public virtual Client Client { get; set; }
    }
}
